### PR TITLE
fixed labeller to keep all input columns

### PR DESCRIPTION
**Pull request by tediyankov**
@mcooper please review the following changes: 
- Added new file `coicop_labeller_keepCols.R` which does the same function as the original labeller, but keeps all columns in the input data. I also added some more comments throughout to enhance readability. 
- Updated the `config.R` file with few shot learning to improve labelling accuracy. It draws on an updated version of `labels.R` which contains an object with identical content to `fewshot_examples.csv'. 
- Added input and outfit files from testing input data column retention fix.

### CODE REVIEW

**Review by mcooper — CHANGES_REQUESTED** [review]
Hey Tedi,

This looks like a good start.  A couple of quick requests/tweaks thought:
* Can you delete `coicop_labeller_keepCols.R` and put your changes into the original `coicop_labeller.R` script?  Lets keep the repo clean and only have one entrypoint script.
* I'm confused why we have `fewshot_examples.csv` but then in `labels.R` we have the same information hardcoded into the script.  Either delete `fewshot_examples.csv` or read from that csv in `labels.R`, but don't have the same data in two different places in the repo.
* I like that you added some testing materials, but I think if we are going to add test data, we should also have some kind of test method or framework.  Maybe add like two lines to the README on how to run the labeller with the test data, or add a quick bash file to the `test/` directory that runs the test, compares the output, and then echos if the test was successful or not.

**Comment by tediyankov** [comment]
Will implement the changes ASAP! Thanks @mcooper

**Comment by tediyankov** [comment]
hi @mcooper ! I have committed all changes addressing your comments. Specifically, I have
- made all the changes in `coicop_labeller.R`
- added a `test.sh` script to execute the test for all input columns remaining in the output file.
- updated the README with a section on testing for input column retention
- I have also removed the `fewshot_examples.CSV` file.

**Review by mcooper — APPROVED** [review]
Hey @tediyankov , the test script looks great.

Please do delete `coicop_labeller_keepCols.R` though, then go ahead and merge.

**Pull request merged**
